{{- if .Values.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "truenas-printserver.fullname" . }}-config
  labels:
    {{- include "truenas-printserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}
---
{{- if .Values.persistence.spool.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "truenas-printserver.fullname" . }}-spool
  labels:
    {{- include "truenas-printserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.spool.size }}
{{- end }}
