###########################################################################
#                                                                         #
# cups-pdf.conf -- CUPS Backend Configuration                            #
#                                                                         #
###########################################################################

Out /var/spool/cups-pdf/${USER}
AnonDirName /var/spool/cups-pdf/ANONYMOUS
AnonUser nobody
Grp lp
UserUMask 0033
